### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by orta**
Yeah - I'm that guy ;)

This looks cool BTW :+1:

### CODE REVIEW

**Comment by agentk** [comment]
I also have references in the jazzy-doc-split branch that will fix the gh-pages site. I'll rebase and fix those while I'm on documentation later.
Cheers @orta

**Comment by orta** [comment]
No worries, and incase you didn't know, [CocoaDocs](http://cocoadocs.org/docsets/ReSwift/0.2.3/) handles that for you ( and we remove references to CocoaPods on the README- so it'd be no different )

**Comment by agentk** [comment]
I really like how easy CocoaDocs make doc generation. I'm using jazzy at the moment for the custom theme, guides support, and grouping of classes. Guide generation is from my jazzy fork at the moment. Ping me if your interested in adding them to CocoaDocs too.

**Comment by orta** [comment]
If you switch to using a `.jazzy.yml` config file CocoaDocs will pick that up, I'm not sure around theming, I've seen your theme, looks nice. Unless a lot of people make their own, I'll probably only have default until I switch to my own

**Pull request merged**
