### PR TITLE
4.1 Release Candidate comparison

### PR DESCRIPTION
**Pull request by mjarvis**
This draft PR is to allow for someone to review a temporary branch I've created for releasing version 4.1 of ReSwift, and is not intended to be merged.

At this time the only thing holding up this release is a possible regression being discussed at https://github.com/ReSwift/ReSwift/issues/394 but I felt like we can get a head start on having approval of this branch for release while we work to resolve that issue.

Based on the conversations in https://github.com/ReSwift/ReSwift/issues/303 this release contains no breaking changes, and should act as an intermediate step before 5.0, which will include a number of breaking changes (removal of `StandardAction`, `AsyncAction`, and their counterparts)

As a summary, here is the Change log for 4.1:

**API Changes:**
- Deprecate `StandardAction` and `StandardActionConvertible` - @mjarvis
    
    - These have been moved to https://github.com/ReSwift/ReSwift-Recorder since they are unnecessary for the base use of ReSwift

- Deprecate `ActionCreator` and `AsyncActionCreator` (#391) - @mjarvis

    - These are deprecated in favor of https://github.com/ReSwift/ReSwift-Thunk

**Other**:
- Add Subscription `skip(when:)` and `only(when:)` (#242) - @mjarvis
- Add `automaticallySkipsRepeats` configuration option to Store initializer (#262) - @DivineDominion
- Improve subscription & state update performance (#325) - @mjarvis
- Enable build settings "Allow app extension API only" (#328) - @oradyvan
- Open `Subscription<State>` to allow external extensions (#383) - @mjarvis

### CODE REVIEW

**Comment by DivineDominion** [comment]
We should not wait for #394. I work with `master` and have 0 problems so far, and unless we can reproduce the issue by @sjmueller, this release would be left in limbo forever. Also, we can always push v4.1.1 a week later if by any chance we should find a problem shortly after the release.

@mjarvis Do you need anything reviewed already?

**Comment by mjarvis** [comment]
@DivineDominion Okay, I'm going to go ahead and cut a 4.1.0 release from this branch, then.

**Comment by mjarvis** [comment]
[4.1.0](https://github.com/ReSwift/ReSwift/releases/tag/4.1.0)  has been released and published to CocoaPods.

**Comment by DivineDominion** [comment]
Great, thank you for the initiative! 🙌

**Pull request closed without merging**
