### PR TITLE
Fixed Xcode 8 Beta 4 issues with new Swift 3 changes.

### PR DESCRIPTION
**Pull request by madhavajay**

### CODE REVIEW

**Comment by Ben-G** [comment]
@madhavajay Thanks a lot for this PR! Can you ensure that the changes don't break with Swift 2.2? See Travis CI failures.

The Xcode 8 test fails are fine for now, as we need to wait for Travis to update.

**Comment by madhavajay** [comment]
Fixed for 2.x, and working in Xcode 8 Beta 4. 😝

**Comment by Ben-G** [comment]
Awesome @madhavajay. Thanks a lot! Can you do me one last favor and remove the trailing whitespace in this line:

```
let contains = subscriptions.contains({ $0.subscriber === subscriber }  )
```

That will get rid of the linter warning.

Thanks so much!

**Comment by madhavajay** [comment]
Sorry, should be all sorted now. 😎

**Comment by Ben-G** [comment]
@madhavajay Thanks a lot for the fixups! We're inviting all contributors to become a member of the ReSwift org. If you are interested you can accept the invite which will make it easier for you to contribute in future!

**Pull request merged**
