### PR TITLE
Fix typo in error message

### PR DESCRIPTION
**Pull request by hkellaway**

### CODE REVIEW

**Review by DivineDominion — APPROVED** [review]
Good catch! Thanks for the fix

**Comment by DivineDominion** [comment]
@hkellaway  Could you rebase or merge the current `master` into your branch to trigger a Travis CI build with the fixes @mjarvis applied today?

**Comment by hkellaway** [comment]
👍 rebased

**Comment by DivineDominion** [comment]
@hkellaway Phew, that seems to have worked. :) Thanks. Sorry I forgot this earlier: Could you add a line to the changelog file?

**Comment by hkellaway** [comment]
Done!

**Pull request merged**
