### PR TITLE
Set CocoaPods documentation URL to GitHub pages

### LINKED ISSUE #56: Add documentation_url in podspec pointing to github pages
Now that we have docs generating into GitHub pages, we can add the documentation_url to the podspec to link the docs link on the CocoaPods page directly to the GitHub pages docs.

Ref: http://guides.cocoapods.org/syntax/podspec.html#documentation_url

### PR DESCRIPTION
**Pull request by agentk**
Closes #56

### CODE REVIEW

**Comment by Ben-G** [comment]
@agentk Unfortunately this will now require a rebase.

**Comment by Ben-G** [comment]
Also, do you want to move your changelog entry to 0.2.6? As 0.2.5 has already :ship:

**Comment by agentk** [comment]
👍 Rebased and fixed the changelog. I remembered to put in the notes from the other docs changes too. Just a brief summary.

**Comment by Ben-G** [comment]
:star2:

**Pull request merged**
