### PR TITLE
missing renames of "MainStore" -> "Store" and "Store" -> "StoreType" in docs and comments

### PR DESCRIPTION
**Pull request by askielboe**
Fixes a few boiler plates, comments and documentations that were using the old naming conventions.

### CODE REVIEW

**Comment by Ben-G** [comment]
@askielboe Thanks for your contribution! I'd like to merge this, however the branch unfortunately became outdated, relative to master (sorry for the delay on our end!). Could you rebase on master so we can merge? :smiley:

**Comment by askielboe** [comment]
Yep, no problem! Thanks for merging this. :)

**Comment by Ben-G** [comment]
Thanks for your contribition @askielboe :tada:! We're inviting all contributors to the ReSwift organization.

Feel free to ignore the invite if you're not interested.

**Comment by askielboe** [comment]
Thank you, I'm honored! :) Really like what you're doing with ReSwift and I'd love to contribute more in the future.

**Pull request merged**
