### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by woin2ee**
- removed content that no longer applicable parts.
- updated to latest version.

### CODE REVIEW

**Comment by DivineDominion** [comment]
I'm fine with this as-is. I mean, who's using Swift 2.2 or 4.x anyway.

Any differing opinions on this, @mjarvis @dani-mp ?

**Comment by dani-mp** [comment]
Sorry, folks, but it's been a while since I was involved in a Swift project so I'm a bit disconnected tbh.

**Comment by woin2ee** [comment]
Additionally, I thought this because discussed dropping support for 4.2 and earlier versions at https://github.com/ReSwift/ReSwift/pull/418

**Review by DivineDominion — APPROVED** [review]
Thanks for this change! I fixed (?) the CI in the meantime so we're good to go

**Comment by DivineDominion** [comment]
We've invited you to join the ReSwift GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/ReSwift/ReSwift/blob/master/CONTRIBUTING.md).

**Pull request merged**
