### PR TITLE
Refactor newState() to apply(state:)

### PR DESCRIPTION
**Pull request by pepasflo**
Thanks so much for writing ReSwift!

Due to my personal baggage from languages of the past, a function named `newState()` is hard-wired in my brain to mean something like "Create and return a new state object".

This PR simply renames `newState()` to `apply(state:)`.

Feel free to merge if you think this is an improvement.  If not, no hard feelings 😁

### CODE REVIEW

**Comment by pepasflo** [comment]
Oops, didn't intend to trigger pod-related changes.

**Comment by DivineDominion** [comment]
I actually like how this reads way better than `newState`.

@mjarvis what do you think, maybe for 5.0 as a breaking API change, and as a deprecation for `4.1.0`?

**Comment by DivineDominion** [comment]
@pepasflo could you undo the CocoaPods related changes for the scope of this PR, and mark `newState` as deprecated without removing it? (`@available(*, deprecated: 1.0, renamed: apply(state:))` or so)

**Comment by pepasflo** [comment]
Sure! 😃

(might not get to it until this evening)

**Comment by DivineDominion** [comment]
@mjarvis We never discussed this anywhere: I like the new wording, but what do you think?

**Comment by danielmartinprieto** [comment]
I agree with @mjarvis. I’m not saying the current function name is perfect, but `apply` seems something more imperative than reactive, I didn’t say anything because I thought you already made the decision, but if one of the main function names of the framework were to be changed, I would spect a big list of alternatives so we can discuss and pick the best one.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brownsoo** [comment]
I also think the current function name is not perfect, but OK. I think `onNewState` seems more appropriate than `apply` in condition to be changed the name. because the function is called reactively. (^^; a minor opinion)

**Comment by pepasflo** [comment]
I'll go ahead and close this for now.  The seed has been planted :)

**Comment by danielmartinprieto** [comment]
Hahaha. Fair enough.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
