### PR TITLE
Added Example Project with SwiftUI

### PR DESCRIPTION
**Pull request by airspeed**
Today I needed to showcase ReSwift to a candidate who was more familiar with SwiftUI than UIKit, unless I am mistaken noone of the sample projects uses SwiftUI, so I ended up rolling my one version of *CounterExample*.  If you think it may be of help for people coming from strong SwiftUI backgrounds feel free to link, fork or otherwise rework.

### CODE REVIEW

**Comment by DivineDominion** [comment]
That's a great idea, thanks for contributing!

We could also move the repo into the ReSwift org if you want.

**Comment by airspeed** [comment]
> That's a great idea, thanks for contributing!
> 
> @airspeed We could also move the repo into the ReSwift org if you want.

👍

**Comment by airspeed** [comment]
> > That's a great idea, thanks for contributing!
> > @airspeed We could also move the repo into the ReSwift org if you want.
> 
> 👍

✅ done

**Review by DivineDominion — APPROVED** [review]

**Comment by DivineDominion** [comment]
Thanks a bunch for doing all this, @airspeed!

**Pull request merged**
