### PR TITLE
Update footer.mustache

### PR DESCRIPTION
**Pull request by wesharehoodies**

### CODE REVIEW

**Comment by DivineDominion** [comment]
Thanks for spotting this!

**Comment by DivineDominion** [comment]
@mjarvis can you do the contributor addition stuff? :)

**Comment by mjarvis** [comment]
Thanks @wesharehoodies! Like all contributors I'll invite you to the ReSwift org. That will make future contributions easier in case you are interested! 🎉

@DivineDominion 😛 Copy-paste-invite!

**Comment by DivineDominion** [comment]
👍  It wasn't worried about the text, I just cannot invite members myself :)

**Comment by mjarvis** [comment]
@DivineDominion oh, sorry! Thats odd -- I'll check in with @Ben-G but I feel like you should have access to that.

**Comment by DivineDominion** [comment]
Don't bother, I'm better at responding to people than managing the repo with my limited OSS experience anyway :)

**Pull request merged**
