### PR TITLE
Action fixes

### PR DESCRIPTION
**Pull request by okla**

### CODE REVIEW

**Comment by Ben-G** [comment]
Hi @okla 

Thanks a lot for this contribution, this piece of code was particularly messy! It mostly looks like some really good improvements. A few notes:

- I like that you introduced constants for the string literals, would you mind removing the `k` prefix? It is not usually used in Swift code
- We're currently successfully avoiding dependencies on `Foundation`, therefore we should not be using `NSNull`. We still have to do the work of removing the Foundation dependency from the project, but at that point it will be a pure Swift project. 

What do you think about the suggested changes? If you agree it would be great if you could also squash your commits using `git rebase` - happy to help if anything is unclear around that.

Thanks a lot for the contribution!

**Comment by okla** [comment]
I don't really know how to use rebase.

**Comment by Ben-G** [comment]
Hey @okla 

> I don't really know how to use rebase.

I wrote a very brief guide on squashing commits with git rebase: http://blog.benjamin-encz.de/post/squashing-commits-with-git-rebase-guide/
I hope it helps! If not, please let me know what's unclear :smiley: 

> Also can't run tests, Xcode says No such module 'Quick'

Did you / can you run:

```
carthage update --no-use-binaries
```

From within the root of the project? This will checkout `Quick` and `Nimble` which are dependencies of the project. The build of these dependencies via carthage fails right now, but that does not impact the ability to run the tests.

Hope this helps!

**Comment by Ben-G** [comment]
@okla The master branch has now been updated to Swift 2.2. Could you rebase against that branch so that we can merge your changes?

Sorry for the long turnaround time!

**Comment by Ben-G** [comment]
@okla Were you able to run the tests locally? Would be great because this PR is still showing some test failures.

Once that is done there only seems to be one hound violation left to fix - then we should be able to get this merged!

**Comment by okla** [comment]
No, I still can't run tests. Also `carthage update --no-use-binaries` fails.

**Comment by Ben-G** [comment]
@okla Can you try

`carthage update --no-use-binaries --platform ios`

**Comment by okla** [comment]
Yes, `carthage update --no-use-binaries --platform ios` works and I've added some fixes to pass tests.

**Comment by Ben-G** [comment]
@okla I've added some small touch ups as part of #113 and merged your changes with that PR. Thanks a lot for your contribution and the patience in the process!

**Pull request closed without merging**
