### PR TITLE
Release 6.0.0

### PR DESCRIPTION
**Pull request by DivineDominion**
- [x] Bump version number in `ReSwift.podspec` and `Info.plist` (We follow [semver](https://semver.org/) - most importantly any breaking API change should result in a major API version bump)
- [x] Add the new version number and the release date to `Changelog.md`
- [ ] Create a tag off of the relevant branch (`master` for regular release) and add the relevant changelog entries to the [release list on GitHub](https://github.com/ReSwift/ReSwift/releases) 
- [ ] Publish the new version to the CocoaPods trunk
- [ ] ✨✨Bonus points ✨✨: for major version`ReSwift` releases, update `ReSwiftRouter` and `GitHubBrowserExample` to use the latest version of `ReSwift`

### CODE REVIEW

**Comment by DivineDominion** [comment]
@mjarvis @dani-mp Please have a look if I thought of everything

**Review by dani-mp — APPROVED** [review]

**Comment by mjarvis** [comment]
Lets update the Travis-CI configuration to use Xcode 12 and latest swift for the main platform test suites.
I also believe we use that somehow for building the pre-compiled option for carthage? If not then we should manually build the precompiled option and include it in release tag as well at the end.

**Comment by DivineDominion** [comment]
Updating Travis is a good catch. Changed this in #450 

We have to run `carthage archive` manually and attach the .zip to the release.

**Comment by mjarvis** [comment]
👍

**Comment by DivineDominion** [comment]
@mjarvis @dani-mp Can you folks try to `carthage build --archive`? It fails for no reason I can parse :/

**Comment by dani-mp** [comment]
There's a nasty bug in Carthage at the moment, but this should work: https://github.com/Carthage/Carthage/issues/3019#issuecomment-701493702

**Comment by DivineDominion** [comment]
Ah, thanks. The script at https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323  works.

**Comment by 1oo7** [comment]
Is there some kind of release notes about this?

**Comment by mjarvis** [comment]
@1oo7 All release notes can be found in [CHANGELOG.md](https://github.com/ReSwift/ReSwift/blob/master/CHANGELOG.md#600)

**Pull request merged**
