### PR TITLE
Update docs to denote enum-based actions.

### PR DESCRIPTION
**Pull request by GetToSet**
After adopting ReSwift in some of my projects, I found that combining related actions in enums can result cleaner code which is more readable and maintainable.

This pull request proposes to update related docs to denote this pattern.

### CODE REVIEW

**Comment by DivineDominion** [comment]
These are very valid suggestions! The way you interspersed the info in various places make me wonder: for someone getting started, would it make sense to "refactor" the docs here and make a subsection about the enum-based approach where `Action` declaration and reducer implementation are next to each other?

**Comment by dani-mp** [comment]
I agree with @DivineDominion, but also, although I like the enum-based approach, the Action type is just a protocol, so anyone that knows Swift will also know that you can use other types to conform to that protocol to implement your actions. I'd prefer to keep docs as small and simple as possible.

**Comment by mjarvis** [comment]
I also concur with @dani-mp here. This is a valid approach but in my opinion unnecessary to document.

Another thing to take into account is generally speaking enums should be avoided for "open" (likely to be expanded on) types. Promoting this pattern can result in versioning & breaking changes issues if someone were to publish a public library that exposed actions in this form.
Locally, however, that pattern can be beneficial by forcing implementation of all cases of the switch.

**Comment by GetToSet** [comment]
Thanks for giving suggestions, I'll try to do some refactor, moving related contents to an independent section.

**Comment by DivineDominion** [comment]
@GetToSet Did you have the chance to revise this?

**Comment by GetToSet** [comment]
> @GetToSet Did you have the chance to revise this?

Sorry but currently I have no spare time to further refine these docs. I'll close this pull request.

**Pull request closed without merging**
