### PR TITLE
add ReSwift-Thunk Project link to README

### PR DESCRIPTION
**Pull request by DivineDominion**

### CODE REVIEW

**Comment by mjarvis** [comment]
👍 Looks good, but I'd like to wait until that project is ready to use before this gets merged.

**Comment by DivineDominion** [comment]
Of course :)

**Comment by DivineDominion** [comment]
@mjarvis the time has come :)

**Comment by mjarvis** [comment]
@DivineDominion ReSwift-Thunk does not appear to have a published release yet -- I think it should be available via carthage & cocoapods before we link to it.

**Comment by danielmartinprieto** [comment]
I had some problems using Carthage today in a macOS project checking if the integration works. I think something is not working but I’ll fix it. Then we can do the Cocoapods thing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DivineDominion** [comment]
Very good points. I'll be patient 🙇‍♂️

**Pull request merged**
