### PR TITLE
Updates StoreType.swift to have @available annotation

### PR DESCRIPTION
**Pull request by alexwhb**
XCode will not allow my WatchOS project to build without this.

### CODE REVIEW

**Review by DivineDominion — CHANGES_REQUESTED** [review]
Thanks for looking into this! I don't recall this was ever a problem. Which Xcode are you using?

Also, could you pick the lowest possible versions? Should be declared in the project itself, or the .podspec -- e.g. I'm using ReSwift in an app targeting macOS 10.11 no problem, but this change would break that.

**Comment by alexwhb** [comment]
I'm using Xcode 12.5 with swiftUI on watchOS. I'm no longer using pods. I'm using swiftPM which is, I believe, what's causing the discrepancy.

**Comment by DivineDominion** [comment]
@alexwhb Oh sorry, I didn't notice this was merging into @mjarvis's branch! Nevermind then :)

**Comment by mjarvis** [comment]
@alexwhb Hi! In my opinion, this branch is not currently the "best" solution for integrating with SwiftUI.

Please see the discussion in https://github.com/ReSwift/ReSwift/issues/455 -- There are a few lightweight wrappers that require zero changes to the ReSwift source code.

**Comment by alexwhb** [comment]
@mjarvis awesome! I'll check that issue out. Thanks for letting me know.

**Comment by DivineDominion** [comment]
How do you want to proceed with the PR, folks?  Close or change? @alexwhb @mjarvis

**Comment by DivineDominion** [comment]
Am closing due to inactivity.

**Pull request closed without merging**
