### PR TITLE
Swift 2.2 fixes

### PR DESCRIPTION
**Pull request by okla**

### CODE REVIEW

**Comment by albinekcom** [comment]
You need to change from: `osx_image: xcode7.2` to `osx_image: xcode7.3` in `.travis.yml` file to fix building. Xcode 7.3 is supporting Swift 2.2.

**Comment by Ben-G** [comment]
@okla, as @albinekcom mentioned, we'll need to update Travis config before merging this. Sorry for the delay & thanks :tada:

**Comment by agentk** [comment]
Hi @okla :wave:, did you want add the travis changes and squash the history? I'm happy help you get it fixed if you have any questions, or I can take over the PR for you if you would prefer.

**Comment by okla** [comment]
@agentk Hi, you can take it, thanks.

**Comment by agentk** [comment]
Cheers @okla.
Closing as the changes are all in #107 now.

**Pull request closed without merging**
