### PR TITLE
[Reducer] Make Reducer a Function Type

### PR DESCRIPTION
**Pull request by Ben-G**
The renewed discussion on #118 has finally pushed me to actually try out this implementation. Looks great to me. We are already recommending composing reducers through composition as shown in: https://github.com/ReSwift/GitHubBrowserExample/blob/master/SwiftFlowGitHubBrowser/Reducers/AppReducer.swift

This change makes the API more consistent with the recommendation. **Best of all this, change is almost backwards compatible**. Instead of passing a free function you can pass a reference to a method of an instance.

I've done this for all of the unit tests. If we were to merge this I would clean up some of the unit tests (the ones that don't need mocking and thus have stateless reducers) to use free functions instead of types for reducers.

### CODE REVIEW

**Comment by Ben-G** [comment]
Ping for discussion: @agentk @DivineDominion @Qata

**Comment by Qata** [comment]
Looks good to me 👍

**Comment by agentk** [comment]
Nice! Once less call needing to force cast too 👌

**Comment by DivineDominion** [comment]
Good job 👏 Solves quite a few cumbersome quirks with the reducer types and looks very straightforward. Going to migrate TableFlip and the demo app as soon as this is integrated in the next release.

**Comment by kouky** [comment]
Nice work on this, stripped away a bunch of unnecessary structs 💯

**Pull request merged**
